=== Varzk-Krethalen/Uni-Exercises-And-Coursework/First Year/Web Dev/daswebsite/students.dtd
<!ELEMENT students (student)*>
<!ELEMENT student (name, dob, course, dep, level)>
<!ELEMENT name (firstname, middlenames, lastname)>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT middlenames (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT dep (#PCDATA)>
<!ELEMENT level (#PCDATA)>
<!ATTLIST student
	id CDATA #REQUIRED
	>

=== Varzk-Krethalen/Uni-Exercises-And-Coursework/First Year/Web Dev/daswebsite/students.xml
<?xml version="1.0"?>
<!DOCTYPE students SYSTEM "itsuite.it.brighton.ac.uk/adws10/daswebsite/students.dtd">
<students>
	<student id="168345233">
		<name>
			<firstname>John</firstname>
			<middlenames>Algernon</middlenames>
			<lastname>Smith</lastname>
		</name>
		<dob>1-1-1034</dob>
		<course>2345</course>
		<dep>CME</dep>
		<level>4</level>
	</student>
</students>
